version: "3"
services:
  kademliaMain:
    image: larjim/kademlialab:latest
    stdin_open: true
    tty: true
    volumes:
      -  ./DeployedCode:/kademlia/bin
#    deploy:
#      replicas: 1 
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
#      restart_policy:
#        condition: on-failure
#    ports:
#      - "4000:80"
    networks:
      kademlia_network:
        ipv4_address: 172.16.238.10

  kademliaNodes:
    image: larjim/kademlialab:latest
    stdin_open: true
    tty: true
    volumes:
      -  ./DeployedCode:/kademlia/bin
    depends_on:
      - "kademliaMain"
#    ports:
#      - "4000:80"
    networks:
      - kademlia_network
      
networks:
  kademlia_network:
    ipam:
      config:
      -
        subnet: 172.16.238.0/24