version: "3"
services:
  kademliaMain:
    image: golang:1.11.0-alpine3.8
    stdin_open: true
    tty: true
    volumes:
      -  ./dev:/kademlia/bin
    working_dir: /kademlia/bin
    command: go run initialize.go 10000
    ports:
      - "8080:80"
    networks:
      kademlia_network:
        ipv4_address: 172.16.238.10

  kademliaNodes:
    image: golang:1.11.0-alpine3.8
    stdin_open: true
    tty: true
    volumes:
      -  ./dev:/kademlia/bin
    working_dir: /kademlia/bin
    command: go run initialize.go 172.16.238.10 10000 10000
    depends_on:
      - "kademliaMain"
 #   ports:
#      - "4000:80"
    networks:
      - kademlia_network
      
  kademliaTest:
    image: golang:1.11.0-alpine3.8
    stdin_open: true
    tty: true
    volumes:
      -  ./dev:/kademlia/bin
    working_dir: /kademlia/bin
    depends_on:
      - "kademliaMain"
#    ports:
#      - "4000:80"
    networks:
      - kademlia_network
      
networks:
  kademlia_network:
    ipam:
      config:
      -
        subnet: 172.16.238.0/24