version: "3"
services:
  Main:
    image: kademlia:latest
    stdin_open: true
    tty: true
    working_dir: /kademlia/bin
#    deploy:
#      mode: global
#      replicas: 1
    command: ./initialize 10000
    networks:
      kademlia_network:
        ipv4_address: 172.25.0.3

  Nodes:
    image: kademlia:latest
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
    working_dir: /kademlia/bin
    command: ./initialize Main 10000 10000
    depends_on:
      - "Main"
    networks:
      - kademlia_network
      
  Test:
    image: kademlia:latest
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
    working_dir: /kademlia/bin
#    command: ./initialize Main 10000 10000
    depends_on:
      - "Main"
    networks:
      - kademlia_network
      
      
networks:
  kademlia_network:
    driver: bridge
    internal: false
    external: true
    ipam:
      config:
      -
        subnet: 172.25.0.0/16